### ISSUE TITLE
Whether to use prabinrath/dynamicslamtool or WYW0/Dynamic-object-detection-for-unstructured-road as a base

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/dynamic_slam_tool#3]
**概要**
- Reference: #1 
- [prabinrath/dynamicslamtool](https://github.com/prabinrath/dynamicslamtool)
  - 製作者の[論文](https://onlinelibrary.wiley.com/doi/pdf/10.1002/eng2.12275)に記載されているリポジトリ
  - 動作せず
- [WYW0/Dynamic-object-detection-for-unstructured-road](https://github.com/WYW0/Dynamic-object-detection-for-unstructured-road)
  - dynamicslamtoolとほぼ同じものが置かれているリポジトリ
  - READMEとライセンスが書き換わっている
  - launchファイルを実行すると動作する
  - ファイルを比較するとdynamicslamtoolにファイルや関数が追記されている
  - コミットログがファイルコピーと無意味なマージコミットしかない

上記のどちらのリポジトリをforkして作業するべきかについて検討
作業内容はあまり変わらないため、基本的にはどちらを使用しても良い

**目的**
今後開発をすすめるに際して扱いやすい状態になることが望ましい。
- fork元に修正があった際に取り込むことを目的とするなら本家の[prabinrath/dynamicslamtool](https://github.com/prabinrath/dynamicslamtool)
- fork元からの変更内容を見やすくしたい場合は[WYW0/Dynamic-object-detection-for-unstructured-road](https://github.com/WYW0/Dynamic-object-detection-for-unstructured-road)

**提案内容**
論文に紹介されている本家の[prabinrath/dynamicslamtool](https://github.com/prabinrath/dynamicslamtool)を使用するほうが汎用性はある
[WYW0/Dynamic-object-detection-for-unstructured-road](https://github.com/WYW0/Dynamic-object-detection-for-unstructured-road)の変更を取り込んだ時点でライセンスに問題があると判断する場合は[WYW0/Dynamic-object-detection-for-unstructured-road](https://github.com/WYW0/Dynamic-object-detection-for-unstructured-road)をforkして使用するほうがよい
他に意見がればコメントください

**タスク**
- [ ]  [prabinrath/dynamicslamtool](https://github.com/prabinrath/dynamicslamtool)と[WYW0/Dynamic-object-detection-for-unstructured-road](https://github.com/WYW0/Dynamic-object-detection-for-unstructured-road)のどちらをforkして作業するか決める

**Comment by Tacha-S** [comment]
https://github.com/sbgisen/dynamic_slam_tool/pull/1/commits/43836335dbb5800badd1852c5a03606f2de9e73a が https://github.com/WYW0/Dynamic-object-detection-for-unstructured-road/commit/2ca00d6dd8633db44d4d3c45adfe0cc1276948bf と同一であるならばcommit authorを @nyxrobotics にしてしまっているから誰の成果かわからなくなっています。
~~MITはライセンス的には非常に寛容なほうなのでcommit authorに入れる(+Readmeに書く)程度でクリアできるでしょう。~~
元がGPLなのでGPLじゃないとだめですね本家一択です

PRに関しては本家に対してwyw0のcommit + @nyxrobotics のcommitにすればよかったのでは？

PRのレビュー内容としてはとりあえずなんか動いたから論文との整合性をチェックしてほしいということですか？

**Comment by nyxrobotics** [comment]
wyw0のcommitをオーナー変えずに分けてみます。
レビューしてほしかったものにこのあたりのことを含むで今の流れであっています。

**Comment by nyxrobotics** [comment]
WYW0のmainをfeature/import_WYW0ブランチにマージし、その後不要な変更を戻す＋追加ファイルのフォーマットという形でコミットログ作ってforce pushします。
